### ISSUE TITLE
ay kent plei

### ISSUE THREAD

**Issue by belyy1337** [saqura1337/csgo-legit-base#3]
chit plei bed delit 4it from guthab

**Comment by c475x** [comment]
nub lern hau tu pro geim

**Comment by belyy1337** [comment]
onli nub pleing vith 4it cheet plei bet💀💀

**Comment by c475x** [comment]
yee lern hau to pley vith aut haks or yu nublo✅

**Comment by saqura1337** [comment]
FAK U
